# Generated by Django 3.0.3 on 2020-04-21 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodComponent',
            fields=[
                ('bloodcomponentid', models.AutoField(primary_key=True, serialize=False)),
                ('bloodcomponent', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'db_table': 'donor_bloodcomponent',
            },
        ),
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('bloodtypeid', models.AutoField(primary_key=True, serialize=False)),
                ('bloodtype', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'db_table': 'donor_bloodtype',
            },
        ),
        migrations.CreateModel(
            name='BloodVolume',
            fields=[
                ('bloodvolumeid', models.AutoField(primary_key=True, serialize=False)),
                ('bloodvolume', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'db_table': 'donor_bloodvolume',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donorid', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('donorname', models.CharField(max_length=4)),
                ('sex', models.CharField(max_length=1)),
                ('birth', models.DateField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('bloodtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.BloodType')),
            ],
            options={
                'db_table': 'donor_donor',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BigIntegerField(unique=True)),
                ('address', models.CharField(max_length=50)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('personresponsible', models.CharField(max_length=50)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Donor.Donor')),
            ],
            options={
                'db_table': 'donor_person',
            },
        ),
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('bloodid', models.AutoField(primary_key=True, serialize=False)),
                ('bloodplace', models.CharField(max_length=50)),
                ('bloodcreate', models.DateField()),
                ('bloodmodify', models.DateTimeField(auto_now=True)),
                ('bloodresponsible', models.CharField(max_length=50)),
                ('bloodcomponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.BloodComponent')),
                ('blooddonor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.Donor')),
                ('bloodvolume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.BloodVolume')),
            ],
            options={
                'db_table': 'donor_blood',
            },
        ),
    ]
