# Generated by Django 3.0.3 on 2020-04-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dusername', models.CharField(max_length=100, unique=True)),
                ('dpassword', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doctor_doctors',
            },
        ),
    ]
